micronaut:
  application:
    name: where-to-refuel-server
  server:
    cors:
      enabled: true
      configurations:
        web:
          maxAge: 28800 # 8 hours
          allowedOrigins:
            - ^http(|s):\/\/(|www)\.webdude\.eu$
  http:
    services:
      fuelowebsite:
        urls:
          - https://bg.fuelo.net
        pool:
          enabled: true
          max-connections: 50
      fuelo:
        urls:
          - https://fuelo.net
        pool:
          enabled: true
          max-connections: 50
      bing:
        urls:
          - https://dev.virtualearth.net
        pool:
          enabled: true
          max-connections: 50
bing:
  base: REST
  version: v1
